[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Serve index.html for all routes (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
